name: aws s3 + cloudfront CI/CD

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Node 설치
        uses: actions/setup-node@v4

      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: nvm을 활용한 프로젝트의 Node 설치
        uses: irby/setup-node-nvm@master

      - name: yarn 설치
        run: |
          npm install -g yarn
          yarn --version

      - name: 패키지 설치
        run: |
          yarn install

      - name: 빌드
        run: |
          yarn build
